import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Toaster } from 'sonner';
import { CalculatorProvider } from '@/context/CalculatorContext'
import { CarsProvider } from '@/context/CarsContext'
import { HomeProvider } from '@/context/HomeContext'
import { ClerkProvider } from '@clerk/nextjs'

const poppinsFont = Poppins({ weight: ['200', '300', '400', '500', '600'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppinsFont.className} overflow-x-hidden overflow-y-auto`}>
        <ClerkProvider appearance={{
          variables: {
            colorBackground: 'rgba(255, 255, 255, .9)',
            colorPrimary: '#6432CF',
            colorText: 'black',
            colorTextSecondary: '#4279CC',
            colorInputBackground: 'rgba(255, 255, 255, .5)',
            colorInputText: 'black',
          }
        }}>
          <HomeProvider>
            <CalculatorProvider>
              <CarsProvider>
                {children}
              </CarsProvider>
            </CalculatorProvider>
          </HomeProvider>
          <Toaster richColors />
        </ClerkProvider>
      </body>
    </html>
  )
}
