import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppinsFont = Poppins({ weight: ['200', '300', '400', '500', '600'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: { children: React.ReactNode | any }) {
  return (
    <html lang="en">
      <body className={`container mx-auto ${poppinsFont.className}`}>
        {
          children
        }
      </body>
    </html>
  )
}
